language: node_js
node_js:
  - "8.2.1"
  - "10"
cache:
  yarn: true
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
script:
  - yarn run build
  - yarn run ci:test
before_script:
  - touch .env
  - echo NODE_ENV=production >> .env
